FROM node:12.16.2-alpine

WORKDIR /app

# Install Lerna
COPY package.json .
RUN npm install

# Copy packages and service code
COPY packages ./packages
COPY services/alert ./services/alert

# Bootstrap dependencies
COPY lerna.json .
RUN npm run bootstrap

CMD [ "npm", "--prefix", "services/alert", "run", "dev" ]

