language: node_js

node_js:
  - '12'

services:
  - docker
  - mongodb

cache: npm

install:
  - npm install
  - npm run bootstrap

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint
  - npm run coverage

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l javascript -r coverage/lcov.info

deploy:
  # Transport service
#   - provider: script
#     script: bash deploy.sh development transport
#     on:
#       branch: development
#   - provider: script
#     script: bash deploy.sh production transport
#     on:
#       branch: master
#   # Alert service
#   - provider: script
#     script: bash deploy.sh development alert
#     on:
#       branch: development
#   - provider: script
#     script: bash deploy.sh production alert
#     on:
#       branch: master
  # Api gateway
  - provider: script
    script: bash deploy.sh development gateway
    on:
      branch: fix-gateway-deploy
    #   branch: development
  - provider: script
    script: bash deploy.sh production gateway
    on:
      branch: master
