version: '3'

services:
  transport-service:
    image: tralert-transport-service
    container_name: tralert-transport-service
    build:
      context: .
      dockerfile: ./services/transport/Dockerfile
    env_file: .env
    environment:
      - LOGS_TOKEN=${TRANSPORT_LOGS_TOKEN}
    ports:
      - '5000:5000'

  alert-service:
    image: tralert-alert-service
    container_name: tralert-alert-service
    build:
      context: .
      dockerfile: ./services/alert/Dockerfile
    env_file: .env
    environment:
      - LOGS_TOKEN=${ALERT_LOGS_TOKEN}
      - AUTH0_CLIENT_ID=${ALERT_AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${ALERT_AUTH0_CLIENT_SECRET}
      - MONGODB_URI=mongodb://tralert-alert-service-db:27017/alerts
      - TRANSPORT_SERVICE_URL=http://tralert-transport-service:5000
    ports:
      - '5001:5001'
    depends_on:
      - alert-service-db

  alert-service-db:
    image: mongo
    container_name: tralert-alert-service-db
    ports:
      - '27017:27017'

  auth-service:
    image: tralert-auth-service
    container_name: tralert-auth-service
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    env_file: .env
    environment:
      - LOGS_TOKEN=${AUTH_LOGS_TOKEN}
      - AUTH0_CLIENT_ID=${AUTH_AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH_AUTH0_CLIENT_SECRET}
    ports:
      - '5002:5002'

  gateway-service:
    image: tralert-gateway-service
    container_name: tralert-gateway-service
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
    env_file: .env
    environment:
      - TRANSPORT_SERVICE_URL=http://tralert-transport-service:5000
      - ALERT_SERVICE_URL=http://tralert-alert-service:5001
      - AUTH_SERVICE_URL=http://tralert-auth-service:5002
    ports:
      - '9080:9080'

  web-service:
    image: tralert-web-service
    container_name: tralert-web-service
    build:
      context: .
      dockerfile: ./services/web/Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=production
      - REACT_APP_AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - PORT=4000
    ports:
      - '4000:4000'
