version: '3'

services:
  transport-service:
    image: tralert-transport-service-dev
    container_name: tralert-transport-service-dev
    build:
      context: .
      dockerfile: ./services/transport/Dockerfile
    env_file: ./services/transport/.env
    ports:
      - '5000:5000'
      - '9229:9229'
    command: npm --prefix services/transport run docker:dev
    volumes:
      - ./packages:/app/packages
      - ./services/transport:/app/services/transport
      - /app/node_modules

  alert-service:
    image: tralert-alert-service-dev
    container_name: tralert-alert-service-dev
    build:
      context: .
      dockerfile: ./services/alert/Dockerfile
    env_file: ./services/alert/.env
    environment:
      - MONGODB_URI=mongodb://alert-service-db:27017/alerts
      - TRANSPORT_SERVICE_URL=http://transport-service:5000
    ports:
      - '5001:5001'
      - '9230:9229'
    command: npm --prefix services/alert run docker:dev
    volumes:
      - ./packages:/app/packages
      - ./services/alert:/app/services/alert
      - /app/node_modules
    depends_on:
      - alert-service-db

  alert-service-db:
    image: mongo
    container_name: tralert-alert-service-db-dev
    ports:
      - '27017:27017'

  gateway-service:
    image: tralert-gateway-service-dev
    container_name: tralert-gateway-service-dev
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
    env_file: ./services/gateway/.env
    environment:
      - TRANSPORT_SERVICE_URL=http://transport-service:5000
      - ALERT_SERVICE_URL=http://alert-service:5001
    ports:
      - '9080:9080'
    volumes:
      - ./services/gateway/config/gateway.config.yml:/var/lib/eg/gateway.config.yml

  web-service:
    image: tralert-web-service-dev
    container_name: tralert-web-service-dev
    stdin_open: true
    build:
      context: .
      dockerfile: ./services/web/Dockerfile.dev
    env_file: ./services/web/.env
    ports:
      - '4000:4000'
    volumes:
      - ./services/web:/app/services/web
      - /app/node_modules
