version: '3'

services:
  transport-service:
    image: transport-service
    container_name: transport-service-dev
    build:
      context: .
      dockerfile: ./services/transport/Dockerfile.dev
    env_file: ./services/transport/.env
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - /app/node_modules

  alert-service:
    image: alert-service
    container_name: alert-service-dev
    build:
      context: .
      dockerfile: ./services/alert/Dockerfile.dev
    env_file: ./services/alert/.env
    environment:
      - MONGODB_URI=mongodb://alert-service-db:27017/alerts
      - TRANSPORT_SERVICE_URL=http://transport-service:5000
    ports:
      - '5001:5001'
    volumes:
      - .:/app
      - /app/node_modules

  alert-service-db:
    image: mongo
    container_name: alert-service-db-dev
    ports:
      - '27017:27017'
