version: '3'

services:
  tralert-transport-service:
    image: tralert-transport-service
    container_name: tralert-transport-service
    build:
      context: .
      dockerfile: ./services/transport/Dockerfile
    env_file: .env
    environment:
      - LOGS_TOKEN:${TRANSPORT_LOGS_TOKEN}
    ports:
      - '5000:5000'

  tralert-alert-service:
    image: tralert-alert-service
    container_name: tralert-alert-service
    build:
      context: .
      dockerfile: ./services/alert/Dockerfile
    env_file: .env
    environment:
      - LOGS_TOKEN:${ALERT_LOGS_TOKEN}
      - MONGODB_URI=mongodb://tralert-alert-service-db:27017/alerts
      - TRANSPORT_URL=http://tralert-transport-service:5000/trains
    ports:
      - '5001:5001'

  tralert-alert-service-db:
    image: mongo
    container_name: tralert-alert-service-db
    ports:
      - '27017:27017'
