# Core
db:
  redis:
    emulate: true
    namespace: EG

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

plugins:
  jwks:
    issuer: https://${AUTH0_DOMAIN}/
    audience: ${AUTH0_AUDIENCE}
    jwksRsa:
      cache: true
      jwksUri: https://${AUTH0_DOMAIN}/.well-known/jwks.json

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
